### ISSUE TITLE
Reporta temperaturas incorrectas

### ISSUE THREAD

**Issue by juanpcapurro** [tanoabeleyra/awinoba-bot-serverless#75]
Ni idea si será un tema del bot o de donde se recolecta la data, pero el bot contesta temperaturas negativas y estoy en remerita:

![image](https://user-images.githubusercontent.com/18706767/178154810-a7a95464-101d-4abc-adbb-677c80cd99a7.png)

**Comment by tanoabeleyra** [comment]
Parece ser un error en la estación, ya que la misma temperatura se muestra en [Windguru](https://www.windguru.cz/station/1736). No veo que exista una relación con la temperatura real, por lo que no puedo realizar ninguna conversión como solución temporal.

P/D: Me alegra saber que el bot sigue vivo después de años sin usarlo

<img width="689" alt="Captura de Pantalla 2022-07-29 a las 16 18 54" src="https://user-images.githubusercontent.com/6851095/181780206-5d6d66d5-7c8c-4599-9715-1f8dd9f918f6.png">
